services:
  caddy:
    build:
      context: ${CADDY_BUILD_PATH}
      dockerfile: Dockerfile
    container_name: caddy
    restart: unless-stopped
    security_opt:
      - label:disable
      - no-new-privileges:true
    cap_add: 
      - NET_BIND_SERVICE  
    read_only: true
    # ports:
    #   - "8080:80"
    #   - "8443:443"
    #   - "8443:443/udp"
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./container-config:/etc/caddy
      - /etc/localtime:/etc/localtime:ro
    networks:
      - reverseproxy-nw
   
networks:
  reverseproxy-nw:
    external: true

# services:
#   caddy:
#     image: docker.io/library/caddy:alpine
#     container_name: caddy
#     restart: unless-stopped
#     security_opt:
#       - label:disable
#     ports:
#       - "8080:80"
#       - "8443:443"
#       - "8443:443/udp"
#     volumes:
#       - ./container-config:/etc/caddy
#       - /etc/localtime:/etc/localtime:ro
#     networks:
#       - reverseproxy-nw

# networks:
#   reverseproxy-nw:
#     external: true

