# services:
#   caddy:
#     image: caddy:<version>
#     restart: unless-stopped
#     ports:
#       - "80:80"
#       - "443:443"
#       - "443:443/udp"
#     volumes:
#       - ./conf:/etc/caddy
#       - ./site:/srv
#       - caddy_data:/data
#       - caddy_config:/config

# volumes:
#   caddy_data:
#   caddy_config:

services:
  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    security_opt:
      - label:disable
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./container-config:/etc/caddy
      - /etc/localtime:/etc/localtime:ro