services:
  guacamole:
    image: docker.io/guacamole/guacamole:1.5.5
    container_name: guacamole
    security_opt:
      - label:disable
    volumes:
      - ./container-data/extensions:/guacamole-home/extensions
      - /etc/localtime:/etc/localtime:ro
    environment:
      - GUACD_HOSTNAME=guacamole-guacd
      - GUACAMOLE_HOME=/guacamole-home
      - POSTGRESQL_HOSTNAME=${POSTGRESQL_HOSTNAME}
      - POSTGRESQL_PORT=${POSTGRESQL_PORT}
      - POSTGRESQL_DATABASE=${POSTGRESQL_DATABASE}
      - POSTGRESQL_USER=${POSTGRESQL_USER}
      - POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD}
      # - OPENID_AUTHORIZATION_ENDPOINT=https://auth.<your-domain>/realms/master/protocol/openid-connect/auth
      # - OPENID_JWKS_ENDPOINT=https://auth.<your-domain>/realms/master/protocol/openid-connect/certs
      # - OPENID_ISSUER=https://auth.<your-domain>/realms/master
      # - OPENID_CLIENT_ID=guacamole
      # - OPENID_REDIRECT_URI=https://remote.<your-domain>/guacamole
    depends_on:
      - guacamole-guacd
      - guacamole-db
    # ports:
    #   - "8081:8080"
    restart: always
    networks:
      - reverseproxy-nw
      - guacamole-nw

  guacamole-guacd:
    image: docker.io/guacamole/guacd:1.5.5
    container_name: guacamole-guacd
    security_opt:
      - label:disable
    networks:
      - guacamole-nw
    restart: always
    volumes:
      - ./container-data/records:/record
      - ./container-data/drive:/drive
      - /etc/localtime:/etc/localtime:ro

  guacamole-db:
    image: docker.io/library/postgres:16
    container_name: guacamole-db
    security_opt:
      - label:disable
    restart: always
    environment:
      - POSTGRES_DB=guacamole_db
      - POSTGRES_USER=guacamole
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./container-data/db:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
      # - /mnt/containers/guacamole/container-data/db-init/initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
      - ./container-data/db-init/initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
    networks:
      - guacamole-nw

networks:
  guacamole-nw:
  reverseproxy-nw:
    external: true

