services:
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:latest
    restart: always
    depends_on:
      - keycloak-db
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: keycloak-db
      KC_DB_URL_PORT: 5432
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USER: keycloak
      KC_DB_PASSWORD: ${KC_DB_PASSWORD}
      KC_DB_SCHEMA: public
      KC_HOSTNAME: ${KC_HOSTNAME}
      KC_PROXY: edge
      KC_HTTP_ENABLED: "true"
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    # ports:
    #   - 8080:8080
    networks:
      - reverseproxy-nw
      - keycloak-nw
    command: start
    # command: >
    #   bash -c "
    #     until pg_isready -h keycloak-db -p 5432 -U keycloak; do
    #       echo 'Waiting for database...'; sleep 2;
    #     done;
    #     /opt/keycloak/bin/kc.sh start
    #   "

  keycloak-db:
    container_name: keycloak-db
    image: docker.io/library/postgres:15
    restart: always
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: ${KC_DB_PASSWORD}
    volumes:
      - ./container-data/db:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    networks:
      - keycloak-nw

networks:
  keycloak-nw:
  reverseproxy-nw:
    external: true

# services:
#   keycloak:
#     container_name: keycloak
#     image: quay.io/keycloak/keycloak:latest
#     restart: always
#     environment:
#       KC_DB: postgres
#       KC_DB_URL: jdbc:postgresql://keycloak-db:5432/keycloak
#       KC_DB_USER: keycloak
#       KC_DB_SCHEMA: public
#       KC_DB_PASSWORD: ${KC_DB_PASSWORD}
#       KC_HOSTNAME: ${KC_HOSTNAME}
#       KEYCLOAK_ADMIN: admin
#       KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
#       KC_PROXY: edge
#       KC_HTTP_ENABLED: "true" 
#     # ports:
#       # - 8080:8080
#     depends_on:
#       - keycloak-db
#     networks:
#       - reverseproxy-nw
#       - keycloak-nw
#     command: start

#   keycloak-db:
#     container_name: keycloak-db
#     image: docker.io/library/postgres:15
#     restart: always
#     security_opt:
#       - label:disable
#     volumes:
#       - ./container-data/db:/var/lib/postgresql/data
#       - /etc/localtime:/etc/localtime:ro
#     environment:
#       POSTGRES_DB: keycloak
#       POSTGRES_USER: keycloak
#       POSTGRES_PASSWORD: ${KC_DB_PASSWORD}
#   #   ports:
#       # - 5432:5432
#     networks:
#       - keycloak-nw

# networks:
#   keycloak-nw:
#   reverseproxy-nw:
#     external: true